"use client";
import {useEffect,useMemo,useState} from "react";
const short=(s:string)=>s.length>22?s.slice(0,12)+"…"+s.slice(-8):s;
function weiToEth(value:string){const raw=String(value||"0").replace(/[^\d]/g,"").replace(/^0+/,"")||"0";const whole=raw.length>18?raw.slice(0,-18):"0";const decimal=raw.slice(-18).padStart(18,"0").slice(0,7).replace(/0+$/,"");return whole+(decimal?"."+decimal:"");}
export default function EthTxPage({params}:{params:{hash:string}}){
 const hash=params.hash??"";const valid=useMemo(()=>/^0x[a-f\d]{64}$/i.test(hash),[hash]);
 const [data,setData]=useState<any>(null);const [network,setNetwork]=useState<any>(null);const [loading,setLoading]=useState(true);const [error,setError]=useState<string|null>(null);const [ai,setAi]=useState<string|null>(null);const [aiLoading,setAiLoading]=useState(false);const [copied,setCopied]=useState(false);
 async function refresh(){if(!valid)return;try{const [a,b]=await Promise.all([fetch("/api/eth/tx/"+hash,{cache:"no-store"}),fetch("/api/network",{cache:"no-store"})]);const j=await a.json();if(!a.ok)throw new Error(j?.error??"Could not load transaction");setData(j);if(b.ok)setNetwork(await b.json());setError(null);}catch(e){setError(e instanceof Error?e.message:"Network unavailable");}finally{setLoading(false);}}
 useEffect(()=>{refresh();const id=setInterval(refresh,15000);return()=>clearInterval(id);},[hash,valid]);
 const confirmed=Boolean(data?.confirmed??(Number(data?.confirmations??0)>0));const failed=Boolean(data?.failed);const blocks=(network?.eth?.recentBlocks??[]).slice(0,5);
 const summary=failed?"Ethereum included your transaction in a block, but the requested operation failed. Network fees may still have been charged. Review the details before trying again.":confirmed?"Your transaction was included in an Ethereum block and has "+String(data?.confirmations??"at least one")+" confirmation(s). The direct ETH amount reported is "+weiToEth(String(data.valueWei??data.value??"0"))+" ETH; token transfers may be separate. Some services wait for additional confirmations before showing funds.":"Your transaction has not been confirmed yet. Ethereum usually adds blocks about every 12 seconds, but your transaction may take longer depending on its fee settings and earlier pending transactions. Keep checking its status before trying to send again.";
 async function explain(){if(!data||aiLoading)return;setAiLoading(true);try{const r=await fetch("/api/ai/explain",{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify({chain:"eth",facts:{confirmed,failed,confirmations:Number(data.confirmations??0),valueEth:weiToEth(String(data.valueWei??data.value??"0")),summary:data.diagnosis?.summary??null}})});const j=await r.json();setAi(r.ok&&typeof j.summary==="string"?j.summary:"Extra explanation is unavailable.");}catch{setAi("Extra explanation is unavailable.");}finally{setAiLoading(false);}}
 if(!valid)return <main className="pt-tx-page"><h1>Check your Ethereum transaction hash</h1><p>An Ethereum transaction hash begins with 0x and contains 64 hexadecimal characters after it.</p><a href="/">← Search again</a></main>;
 return <main className="pt-tx-page pt-tx-eth">
  <div className="pt-tx-back"><a href="/">← Back to explorer</a></div><div className="pt-tx-top"><div><div className="pt-eyebrow">ETHEREUM TRANSACTION TRACKER</div><h1>{failed?"Your Ethereum transaction failed":confirmed?"Your Ethereum transaction is confirmed":"Your Ethereum transaction is waiting"}</h1><p>See what the blockchain says in plain English.</p></div><button onClick={refresh} disabled={loading}>{loading?"Checking…":"↻ Refresh"}</button></div>
  <div className="pt-tx-idbar"><div><span>TRANSACTION HASH</span><code title={hash}>{hash}</code></div><button type="button" onClick={()=>navigator.clipboard?.writeText(hash).then(()=>{setCopied(true);setTimeout(()=>setCopied(false),1800);}).catch(()=>{})}>{copied?"✓ Copied":"Copy ID"}</button></div>
  {error&&<div className="pt-tx-error" role="alert">{error}</div>}
  {loading&&!data&&<div className="pt-tx-loading">Checking the Ethereum network…</div>}
  {data&&<>
   <section className="pt-tx-stage"><div className="pt-tx-stage-head"><div><span className="pt-eyebrow">WHERE IS MY TRANSACTION?</span><h2>{failed?"Included, but failed":confirmed?"Included in a block":"Waiting for a block"}</h2></div><span className={confirmed&&!failed?"pt-tx-state good":"pt-tx-state"}>{failed?"● Failed":confirmed?"● Confirmed":"● Pending"}</span></div>
    <div className="pt-tx-estimate"><span>TRANSACTION STATUS</span><strong>{failed?"Failed":confirmed?"Confirmed":"Pending"}</strong><span>EXPECTED WAIT</span><strong>{confirmed?"Already included":"Not predictable yet"}</strong></div><div className="pt-tx-block-track">
     {!confirmed&&!failed&&<div className="pt-tx-position"><span className="pt-tx-pointer">↓</span><strong>Your transaction is waiting</strong><small>Exact block unknown</small></div>}
     <div className="pt-tx-block-grid">{(blocks.length?blocks:[0,1,2,3,4].map(()=>({height:null,transactionsCount:null,timestamp:null}))).map((block:any,index:number)=><div className="pt-tx-block" key={block.hash??index}><div className="pt-tx-block-label">{index===0?"LATEST BLOCK":"RECENT BLOCK"}</div><div className="pt-tx-block-time">{block.timestamp?"Added":"—"} <span>{block.timestamp?new Date(block.timestamp).toLocaleTimeString([],{hour:"numeric",minute:"2-digit"}):""}</span></div><div className="pt-tx-block-tiles" aria-hidden="true">{Array.from({length:15},(_,i)=><i key={i} style={{opacity:block.transactionsCount==null?.25:i<Math.max(1,Math.min(15,Math.round(Number(block.transactionsCount)/15)))?1:.16}}/>)}</div><strong>#{block.height??"—"}</strong><small>{block.transactionsCount==null?"Live data loading":Number(block.transactionsCount).toLocaleString()+" transactions"}</small></div>)}</div>
     <p className="pt-tx-block-caveat">These are recently added Ethereum blocks, not predictions. Pending transactions cannot be placed into an exact future block reliably.</p>
    </div>
   </section>
   <section className="pt-tx-summary"><div className="pt-eyebrow">THE SHORT ANSWER</div><h2>{failed?"What happened?":confirmed?"Good news—it's confirmed.":"Here's what's happening."}</h2><p>{summary}</p><div className="pt-tx-summary-actions"><button onClick={explain} disabled={aiLoading}>{aiLoading?"Explaining…":"✦ Explain more with AI"}</button><a href={"https://eth.blockscout.com/tx/"+hash} target="_blank" rel="noopener noreferrer">Verify on Blockscout ↗</a></div>{ai&&<p className="pt-tx-ai" role="status">{ai}</p>}</section>
   <section className="pt-tx-details"><div className="pt-eyebrow">IF YOU WANT THE DETAILS</div><h2>Your transaction at a glance</h2><p className="pt-tx-details-intro">These values come from the transaction record, not general network averages.</p><div className="pt-tx-facts"><div><span>Current status</span><strong>{failed?"Failed":confirmed?"Confirmed":"Pending"}</strong><small>What the Ethereum network reports</small></div><div><span>Amount</span><strong>{weiToEth(String(data.valueWei??data.value??"0"))} ETH</strong><small>Amount sent directly in this transaction</small></div><div><span>Confirmations</span><strong>{String(data.confirmations??(confirmed?1:0))}</strong><small>Blocks confirming this transaction</small></div></div><details className="pt-tx-more"><summary>More technical information <span>＋</span></summary><div><p><b>Transaction hash:</b> <code>{hash}</code></p><p><b>From:</b> {short(String(data.from??"—"))}</p><p><b>To:</b> {short(String(data.to??"—"))}</p><p><b>Current gas estimate:</b> {network?.eth?.gasGwei??"—"} Gwei (not the transaction's total fee)</p><button onClick={()=>navigator.clipboard?.writeText(hash)}>Copy transaction hash</button><details><summary>Raw blockchain data</summary><pre>{JSON.stringify(data,null,2)}</pre></details></div></details></section>
  </>}
  <p className="pt-tx-footnote">Updates every 15 seconds · Public blockchain data · No wallet connection required.</p>
 </main>;

}
