"use client";
import "./explorer-dashboard.css";
import {useEffect,useState} from "react";
import Link from "next/link";
type Net={btc?:{pending?:number|null;fastestFee?:number|null;halfHourFee?:number|null;hourFee?:number|null;economyFee?:number|null;minimumFee?:number|null;projectedBlocks?:Array<{position:number;transactionCount:number|null;feeRange:number[]|null;medianFee:number|null}>;latestBlock?:{height:number|null;id:string|null;ageMinutes:number;transactionCount:number|null}|null;recentTransactions?:Array<{id:string;fee:number|null;vsize:number|null}>;congestion?:string;explanation?:string};eth?:{gasGwei?:number|null;latestBlock?:string|number|null;recentBlocks?:Array<{height:number|string|null;hash:string|null;transactionsCount:number|null;timestamp:string|null}>;recentTransactions?:Array<{hash:string;status:string|null;block:number|null}>;explanation?:string}};const fmt=(v:number|null|undefined)=>v==null?"—":new Intl.NumberFormat("en-US",{maximumFractionDigits:2}).format(v);
export default function ChainDashboard({chain}:{chain:"bitcoin"|"ethereum"}){
 const [data,setData]=useState<Net|null>(null);const [loading,setLoading]=useState(true);const [updated,setUpdated]=useState("");
 useEffect(()=>{let active=true;async function refresh(){try{const r=await fetch("/api/network",{cache:"no-store"});if(!r.ok)throw Error();const j=await r.json();if(active){setData(j);setUpdated(new Date().toLocaleTimeString([],{hour:"numeric",minute:"2-digit"}));}}catch{}finally{if(active)setLoading(false)}}refresh();const timer=setInterval(refresh,15000);return()=>{active=false;clearInterval(timer)}},[]);
 const btc=data?.btc,eth=data?.eth,isBtc=chain==="bitcoin";
 const stat=isBtc?[{label:"Waiting transactions",value:fmt(btc?.pending),hint:"Payments waiting for a Bitcoin block"},{label:"Latest block",value:btc?.latestBlock?.height==null?"—":"#"+fmt(btc.latestBlock.height),hint:"Newest confirmed batch of transactions"},{label:"Priority fee guide",value:btc?.fastestFee==null?"—":fmt(btc.fastestFee)+" sat/vB",hint:"Estimated competitive fee rate"},{label:"Network traffic",value:btc?.congestion??"—",hint:"A rough view of how crowded the network is"}]:[{label:"Latest block",value:eth?.latestBlock==null?"—":"#"+eth.latestBlock,hint:"Newest recorded Ethereum block"},{label:"Average gas price",value:eth?.gasGwei==null?"—":fmt(eth.gasGwei)+" Gwei",hint:"Estimated price for one unit of gas"},{label:"Block rhythm",value:"~12 seconds",hint:"Typical Ethereum block interval, not a promise"},{label:"Network",value:"Mainnet",hint:"Ethereum's public production blockchain"}];
 const blocks=isBtc?(btc?.projectedBlocks??[]).slice(0,5).map(b=>({id:"p"+b.position,title:"Next ~"+b.position*10+" min",sub:"Projected block "+b.position,range:b.feeRange?.length?fmt(b.feeRange[0])+"–"+fmt(b.feeRange[1])+" sat/vB":"Fee range unavailable",count:b.transactionCount==null?"Transactions unavailable":fmt(b.transactionCount)+" transactions",href:null as string|null})):(eth?.recentBlocks??[]).slice(0,5).map(b=>({id:b.hash??String(b.height),title:"Block #"+b.height,sub:"Recently recorded",range:"Confirmed block",count:b.transactionsCount==null?"Transaction count unavailable":fmt(b.transactionsCount)+" transactions",href:b.hash?"/eth/block/"+b.hash:null as string|null}));
 const feeLevels=isBtc?[{label:"Higher priority",fee:btc?.fastestFee,wait:"Often next block (~10 min)",note:"A current fee recommendation, not a guarantee"},{label:"Medium priority",fee:btc?.halfHourFee,wait:"Around 30 minutes",note:"Guide for roughly three average Bitcoin blocks"},{label:"Lower priority",fee:btc?.hourFee,wait:"Around 60 minutes",note:"May take longer if the network gets busier"},{label:"Economy",fee:btc?.economyFee,wait:"No dependable time",note:"Lower fees can wait much longer"}]:[{label:"Typical gas price",fee:eth?.gasGwei,wait:"Blocks usually ~12 seconds apart",note:"Actual inclusion depends on your transaction's max fee, priority fee and nonce"}];
 return <div className="pt-dash">
  <div className="pt-dash-top"><div><div className="pt-eyebrow">LIVE NETWORK OVERVIEW</div><h2>What's happening on the {isBtc?"Bitcoin":"Ethereum"} network?</h2><p>A live snapshot of activity, waiting transactions and network costs — with the important numbers explained.</p></div><span className="pt-dash-live">{loading?"Loading live data…":updated?"● Updated "+updated:"● Data unavailable"}</span></div>
  <div className="pt-dash-stats" style={{display:"grid",gridTemplateColumns:"repeat(auto-fit,minmax(190px,1fr))",gap:12}}>{stat.map(x=><div className="pt-dash-stat" key={x.label}><span>{x.label}</span><strong>{x.value}</strong><small>{x.hint}</small></div>)}</div>
  <section className="pt-dash-blocks pt-dash-confirmation" style={{marginTop:32,padding:"28px 0 24px",background:"transparent",border:"none",borderTop:"1px solid #40576a",borderBottom:"1px solid #40576a",borderRadius:0}}>
    <div className="pt-dash-heading" style={{marginBottom:22}}>
      <div className="pt-eyebrow">{isBtc?"LIVE BITCOIN FEE OUTLOOK":"LIVE ETHEREUM BLOCK ACTIVITY"}</div>
      <h3 style={{fontSize:"clamp(22px,2.7vw,30px)",letterSpacing:"-0.025em",margin:"9px 0"}}>{isBtc?"Current estimated transaction confirmation times":"Recently confirmed Ethereum blocks"}</h3>
      <p style={{maxWidth:840,lineHeight:1.7}}>{isBtc?"How quickly could a new Bitcoin transaction confirm? Compare today's recommended fee rates with common confirmation targets. These are network-wide estimates, not a prediction for a specific payment.":"Ethereum usually proposes a block about every 12 seconds. Explore the latest recorded blocks below. A particular transaction can still wait longer if its gas settings or nonce prevent inclusion."}</p>
    </div>
    {isBtc?<div style={{maxWidth:1000}}>
      <div style={{display:"flex",justifyContent:"space-between",alignItems:"center",gap:16,padding:"0 0 12px",borderBottom:"1px solid #40576a",fontSize:10,letterSpacing:"0.1em",fontWeight:700,color:"#9fb6c5"}}><span>CONFIRMATION TARGET</span><span>RECOMMENDED FEE RATE</span></div>
      {[
        {label:"Fastest",time:"~10 min",detail:"Aim for the next block",fee:btc?.fastestFee},
        {label:"Balanced",time:"~30 min",detail:"Within about three blocks",fee:btc?.halfHourFee},
        {label:"Economy",time:"~60 min",detail:"Within about six blocks",fee:btc?.hourFee}
      ].map((item,i)=><div key={item.label} style={{display:"grid",gridTemplateColumns:"minmax(105px,0.8fr) minmax(145px,1.6fr) minmax(110px,1fr)",alignItems:"center",columnGap:18,rowGap:7,padding:"22px 5px",borderBottom:"1px solid #334d60"}}>
        <div style={{display:"flex",alignItems:"center",gap:12}}><span style={{display:"inline-block",width:7,height:7,flexShrink:0,borderRadius:"50%",background:i===0?"#e6c58d":"#819ba9"}}/><strong style={{fontSize:15,color:"#f2f5f8",fontWeight:650}}>{item.label}</strong></div>
        <div style={{display:"flex",flexDirection:"column",gap:5}}><strong style={{fontSize:"clamp(21px,2.5vw,29px)",letterSpacing:"-0.025em",fontWeight:650,color:"#f2d5a3"}}>{item.time}</strong><span style={{fontSize:12,color:"#b4c7d2"}}>{item.detail}</span></div>
        <div style={{textAlign:"right",display:"flex",flexDirection:"column",gap:5}}><strong style={{fontSize:"clamp(17px,2vw,23px)",fontWeight:650,color:"#e9f0f5"}}>{item.fee==null?"—":fmt(item.fee)+" sat/vB"}</strong><span style={{fontSize:11,color:"#9eb7c6"}}>Current estimate</span></div>
      </div>)}
      <p style={{fontSize:12,lineHeight:1.75,color:"#b6c9d4",margin:"18px 0 0"}}><strong style={{color:"#e9c995"}}>What does sat/vB mean?</strong> It is the fee rate per unit of transaction size. Higher rates generally compete more strongly for limited block space. Actual confirmation can be faster or slower than these targets because Bitcoin blocks do not arrive on a fixed schedule.</p>
      <p style={{fontSize:11,lineHeight:1.7,color:"#9eb4c2",margin:"10px 0 0"}}>Estimates from current network fee recommendations. Search your transaction above to examine its own fee and status.</p>
    </div>:<div className="pt-dash-eth-blocks" style={{display:"flex",flexDirection:"column",borderTop:"1px solid #456173"}}>{blocks.length?blocks.map((b,i)=><div className="pt-dash-eth-block" style={{display:"flex",alignItems:"center",gap:16,padding:"18px 8px",borderBottom:"1px solid #456173"}} key={b.id}><div className="pt-dash-eth-index" style={{color:"#efd09a",minWidth:32,fontWeight:700}}>{String(i+1).padStart(2,"0")}</div><div style={{flex:1,minWidth:0,display:"flex",flexDirection:"column",gap:7}}><strong style={{fontSize:16}}>{b.title}</strong><small style={{color:"#b9cdd8",fontSize:12}}>{b.count} · Confirmed on Ethereum</small></div>{b.href?<Link href={b.href}>View block →</Link>:null}</div>):<p className="pt-dash-empty">Recent blocks are temporarily unavailable.</p>}</div>}
  </section>
  {!isBtc?<section className="pt-dash-fees"><div className="pt-dash-heading"><div className="pt-eyebrow">ETHEREUM GAS</div><h3>What do Ethereum gas fees mean?</h3><p>Gas is the computation a transaction uses. Gwei is the unit used to quote gas prices. A typical block arrives roughly every 12 seconds, but this does not guarantee when an individual transaction will be included.</p></div><div className="pt-dash-feegrid">{feeLevels.map(f=><div className="pt-dash-feecard" key={f.label}><span>{f.label}</span><strong>{f.fee==null?"—":fmt(f.fee)+" Gwei"}</strong><b>{f.wait}</b><small>{f.note}</small></div>)}</div><p className="pt-dash-disclaimer">Ethereum does not have a dependable universal gas-price-to-minutes table. Search a transaction to see its actual status and any reported delay factors.</p></section>:null}
  <section className="pt-dash-recent"><div className="pt-dash-heading"><div><div className="pt-eyebrow">LIVE TRANSACTION ACTIVITY</div><h3>Recent {isBtc?"Bitcoin":"Ethereum"} transactions</h3><p>Choose any transaction to see its status, summary, and full technical record.</p></div></div><div className="pt-dash-txlist">{isBtc?(btc?.recentTransactions??[]).slice(0,5).map(t=><Link href={"/btc/"+t.id} className="pt-dash-tx" key={t.id}><div><b>{t.id.slice(0,16)}…{t.id.slice(-9)}</b><small>Waiting in the mempool · {t.fee==null?"Fee unavailable":fmt(t.fee)+" sats total fee"}</small></div><span>Explain →</span></Link>):(eth?.recentTransactions??[]).slice(0,5).map(t=><Link href={"/eth/"+t.hash} className="pt-dash-tx" key={t.hash}><div><b>{t.hash.slice(0,16)}…{t.hash.slice(-9)}</b><small>{t.status??"Status unavailable"}{t.block==null?"":" · Block #"+t.block}</small></div><span>Explain →</span></Link>)}{!(isBtc?btc?.recentTransactions?.length:eth?.recentTransactions?.length)?<p className="pt-dash-empty">Recent transactions are temporarily unavailable.</p>:null}</div></section>
  <section className="pt-dash-summary"><div className="pt-eyebrow">THE SIMPLE EXPLANATION</div><h3>What does all this mean?</h3><p>{isBtc?btc?.explanation??"Bitcoin transactions wait in a shared pool until miners add them to a block. The fee rate affects priority, but there is no guaranteed wait time.":eth?.explanation??"Ethereum transactions are processed in blocks, and gas fees pay for the work involved. A transaction's actual wait depends on its fee settings and other pending transactions."}</p><p>{isBtc?"If you are waiting on a Bitcoin payment, search its transaction ID above. We'll compare its actual fee with current conditions and explain what you can do next.":"If you are waiting on an Ethereum transfer, search its transaction hash above. We'll explain whether it succeeded, failed, or is still waiting, and show token movements when available."}</p><details><summary>More technical context ＋</summary><p>{isBtc?"Mempool: the waiting area for unconfirmed transactions. Sats: Bitcoin's smallest units. sat/vB: the fee rate per virtual byte. A block: a batch of confirmed transactions. Projections show possible miner selection, not guaranteed placement.":"Gas: computational work required by Ethereum. Gwei: one-billionth of an ETH. Nonce: the transaction sequence number from an address. A block: a batch of recorded transactions. A contract call can move tokens even if no ETH is directly transferred."}</p></details></section>
  <p className="pt-dash-source">Data from mempool.space and Blockscout · Refreshed approximately every 15 seconds while this page is open · Estimates are informational, not guarantees.</p>
 </div>
}