import "./explorer-dashboard.css";
"use client";
import {useEffect,useState} from "react";
import Link from "next/link";
type Net={btc?:{pending?:number|null;fastestFee?:number|null;halfHourFee?:number|null;hourFee?:number|null;economyFee?:number|null;minimumFee?:number|null;projectedBlocks?:Array<{position:number;transactionCount:number|null;feeRange:number[]|null;medianFee:number|null}>;latestBlock?:{height:number|null;id:string|null;ageMinutes:number;transactionCount:number|null}|null;recentTransactions?:Array<{id:string;fee:number|null;vsize:number|null}>;congestion?:string;explanation?:string};eth?:{gasGwei?:number|null;latestBlock?:string|number|null;recentBlocks?:Array<{height:number|string|null;hash:string|null;transactionsCount:number|null;timestamp:string|null}>;recentTransactions?:Array<{hash:string;status:string|null;block:number|null}>;explanation?:string}};const fmt=(v:number|null|undefined)=>v==null?"—":new Intl.NumberFormat("en-US",{maximumFractionDigits:2}).format(v);
export default function ChainDashboard({chain}:{chain:"bitcoin"|"ethereum"}){
 const [data,setData]=useState<Net|null>(null);const [loading,setLoading]=useState(true);const [updated,setUpdated]=useState("");
 useEffect(()=>{let active=true;async function refresh(){try{const r=await fetch("/api/network",{cache:"no-store"});if(!r.ok)throw Error();const j=await r.json();if(active){setData(j);setUpdated(new Date().toLocaleTimeString([],{hour:"numeric",minute:"2-digit"}));}}catch{}finally{if(active)setLoading(false)}}refresh();const timer=setInterval(refresh,15000);return()=>{active=false;clearInterval(timer)}},[]);
 const btc=data?.btc,eth=data?.eth,isBtc=chain==="bitcoin";
 const stat=isBtc?[{label:"Waiting transactions",value:fmt(btc?.pending),hint:"Payments waiting for a Bitcoin block"},{label:"Latest block",value:btc?.latestBlock?.height==null?"—":"#"+fmt(btc.latestBlock.height),hint:"Newest confirmed batch of transactions"},{label:"Priority fee guide",value:btc?.fastestFee==null?"—":fmt(btc.fastestFee)+" sat/vB",hint:"Estimated competitive fee rate"},{label:"Network traffic",value:btc?.congestion??"—",hint:"A rough view of how crowded the network is"}]:[{label:"Latest block",value:eth?.latestBlock==null?"—":"#"+eth.latestBlock,hint:"Newest recorded Ethereum block"},{label:"Average gas price",value:eth?.gasGwei==null?"—":fmt(eth.gasGwei)+" Gwei",hint:"Estimated price for one unit of gas"},{label:"Block rhythm",value:"~12 seconds",hint:"Typical Ethereum block interval, not a promise"},{label:"Network",value:"Mainnet",hint:"Ethereum's public production blockchain"}];
 const blocks=isBtc?(btc?.projectedBlocks??[]).slice(0,5).map(b=>({id:"p"+b.position,title:"Next ~"+b.position*10+" min",sub:"Projected block "+b.position,range:b.feeRange?.length?fmt(b.feeRange[0])+"–"+fmt(b.feeRange[1])+" sat/vB":"Fee range unavailable",count:b.transactionCount==null?"Transactions unavailable":fmt(b.transactionCount)+" transactions",href:null as string|null})):(eth?.recentBlocks??[]).slice(0,5).map(b=>({id:b.hash??String(b.height),title:"Block #"+b.height,sub:"Recently recorded",range:"Confirmed block",count:b.transactionsCount==null?"Transaction count unavailable":fmt(b.transactionsCount)+" transactions",href:b.hash?"/eth/block/"+b.hash:null as string|null}));
 const feeLevels=isBtc?[{label:"Higher priority",fee:btc?.fastestFee,wait:"Often next block (~10 min)",note:"A current fee recommendation, not a guarantee"},{label:"Medium priority",fee:btc?.halfHourFee,wait:"Around 30 minutes",note:"Guide for roughly three average Bitcoin blocks"},{label:"Lower priority",fee:btc?.hourFee,wait:"Around 60 minutes",note:"May take longer if the network gets busier"},{label:"Economy",fee:btc?.economyFee,wait:"No dependable time",note:"Lower fees can wait much longer"}]:[{label:"Typical gas price",fee:eth?.gasGwei,wait:"Blocks usually ~12 seconds apart",note:"Actual inclusion depends on your transaction's max fee, priority fee and nonce"}];
 return <div className="pt-dash">
  <div className="pt-dash-top"><div><div className="pt-eyebrow">LIVE NETWORK OVERVIEW</div><h2>What's happening on {isBtc?"Bitcoin":"Ethereum"} right now?</h2><p>Start with the simple explanation. Open any record to explore the details.</p></div><span className="pt-dash-live">{loading?"Loading live data…":updated?"● Updated "+updated:"● Data unavailable"}</span></div>
  <div className="pt-dash-stats">{stat.map(x=><div className="pt-dash-stat" key={x.label}><span>{x.label}</span><strong>{x.value}</strong><small>{x.hint}</small></div>)}</div>
  <section className="pt-dash-blocks"><div className="pt-dash-heading"><div><div className="pt-eyebrow">{isBtc?"THE WAITING LINE":"THE BLOCKCHAIN"}</div><h3>{isBtc?"Upcoming Bitcoin blocks":"Recently confirmed Ethereum blocks"}</h3><p>{isBtc?"Each card shows a projected batch of waiting transactions. The minutes are rough illustrations based on Bitcoin's average 10-minute block interval, not a countdown.":"Ethereum produces blocks roughly every 12 seconds. These cards show blocks already recorded on the network."}</p></div></div>
   <div className="pt-dash-blockstrip">{blocks.length?blocks.map((b,i)=><div className={"pt-dash-block pt-dash-block-"+(i%4)} key={b.id}><span className="pt-dash-block-label">{b.sub}</span><strong>{b.title}</strong><b>{b.range}</b><small>{b.count}</small>{b.href?<Link href={b.href}>Open block →</Link>:null}</div>):<p className="pt-dash-empty">Block data is temporarily unavailable.</p>}</div>
  </section>
  <section className="pt-dash-fees"><div className="pt-dash-heading"><div><div className="pt-eyebrow">{isBtc?"BITCOIN FEES":"ETHEREUM GAS"}</div><h3>{isBtc?"How much fee might I need?":"How long might Ethereum take?"}</h3><p>{isBtc?"Bitcoin fees are measured in sat/vB. One sat (satoshi) is one hundred-millionth of a bitcoin; sat/vB measures how much you pay for the size of your transaction.":"Ethereum gas is the fee paid for network computation. Gwei is a tiny unit of ETH used to quote gas prices."}</p></div></div>
   <div className="pt-dash-feegrid">{feeLevels.map((f,i)=><div className="pt-dash-feecard" key={f.label}><span>{f.label}</span><strong>{f.fee==null?"—":fmt(f.fee)+" "+(isBtc?"sat/vB":"Gwei")}</strong><b>{f.wait}</b><small>{f.note}</small></div>)}</div>
   {isBtc?<p className="pt-dash-disclaimer">These are network-wide fee recommendations, not predictions for a specific transaction. Miners choose transactions independently; fees and congestion can change at any time.</p>:<p className="pt-dash-disclaimer">Ethereum does not have a reliable universal “pay X Gwei = wait Y minutes” table. Blocks arrive frequently, but an underpriced or nonce-blocked transaction may wait much longer. Search your transaction for its actual status.</p>}
  </section>
  <section className="pt-dash-recent"><div className="pt-dash-heading"><div><div className="pt-eyebrow">LIVE TRANSACTION ACTIVITY</div><h3>Recent {isBtc?"Bitcoin":"Ethereum"} transactions</h3><p>Choose any transaction to see its status, summary, and full technical record.</p></div></div><div className="pt-dash-txlist">{isBtc?(btc?.recentTransactions??[]).slice(0,5).map(t=><Link href={"/btc/"+t.id} className="pt-dash-tx" key={t.id}><div><b>{t.id.slice(0,16)}…{t.id.slice(-9)}</b><small>Waiting in the mempool · {t.fee==null?"Fee unavailable":fmt(t.fee)+" sats total fee"}</small></div><span>Explain →</span></Link>):(eth?.recentTransactions??[]).slice(0,5).map(t=><Link href={"/eth/"+t.hash} className="pt-dash-tx" key={t.hash}><div><b>{t.hash.slice(0,16)}…{t.hash.slice(-9)}</b><small>{t.status??"Status unavailable"}{t.block==null?"":" · Block #"+t.block}</small></div><span>Explain →</span></Link>)}{!(isBtc?btc?.recentTransactions?.length:eth?.recentTransactions?.length)?<p className="pt-dash-empty">Recent transactions are temporarily unavailable.</p>:null}</div></section>
  <section className="pt-dash-summary"><div className="pt-eyebrow">THE SIMPLE EXPLANATION</div><h3>What does all this mean?</h3><p>{isBtc?btc?.explanation??"Bitcoin transactions wait in a shared pool until miners add them to a block. The fee rate affects priority, but there is no guaranteed wait time.":eth?.explanation??"Ethereum transactions are processed in blocks, and gas fees pay for the work involved. A transaction's actual wait depends on its fee settings and other pending transactions."}</p><p>{isBtc?"If you are waiting on a Bitcoin payment, search its transaction ID above. We'll compare its actual fee with current conditions and explain what you can do next.":"If you are waiting on an Ethereum transfer, search its transaction hash above. We'll explain whether it succeeded, failed, or is still waiting, and show token movements when available."}</p><details><summary>More technical context ＋</summary><p>{isBtc?"Mempool: the waiting area for unconfirmed transactions. Sats: Bitcoin's smallest units. sat/vB: the fee rate per virtual byte. A block: a batch of confirmed transactions. Projections show possible miner selection, not guaranteed placement.":"Gas: computational work required by Ethereum. Gwei: one-billionth of an ETH. Nonce: the transaction sequence number from an address. A block: a batch of recorded transactions. A contract call can move tokens even if no ETH is directly transferred."}</p></details></section>
  <p className="pt-dash-source">Data from mempool.space and Blockscout · Refreshed approximately every 15 seconds while this page is open · Estimates are informational, not guarantees.</p>
 </div>
}