import ChainSearch from "../components/ChainSearch";
import Link from "next/link";
export const metadata={title:"Ethereum Explorer | Pending Tracker",description:"Explore Ethereum blocks, transactions, gas fees and smart-contract activity in plain English."};
async function get(url:string){try{const r=await fetch(url,{next:{revalidate:15},signal:AbortSignal.timeout(7000)});return r.ok?await r.json():null}catch{return null}}
const n=(v:number|null|undefined)=>v==null?"—":new Intl.NumberFormat("en-US").format(v);
export default async function EthereumExplorer(){
 const [blocks,transactions,stats]=await Promise.all([get("https://eth.blockscout.com/api/v2/blocks?type=block"),get("https://eth.blockscout.com/api/v2/transactions?filter=validated"),get("https://eth.blockscout.com/api/v2/stats")]);
 const recent=Array.isArray(blocks?.items)?blocks.items.slice(0,12):[];
 const txs=Array.isArray(transactions?.items)?transactions.items.slice(0,12):[];
 return <main className="pt-chain-page">
  <div className="pt-chain-breadcrumb"><Link href="/">Home</Link><span> / </span> Ethereum Explorer</div>
  <div className="pt-chain-hero"><div className="pt-chain-symbol pt-chain-ethereum">◆</div><div><div className="pt-eyebrow">ETHEREUM BLOCKCHAIN EXPLORER</div><h1>Explore Ethereum.</h1><p>Understand Ethereum activity at a glance. Browse blocks, transactions, tokens and contracts, with straightforward summaries and deeper technical records when you need them.</p></div></div>
  <div className="pt-chain-search"><h2>Find a Ethereum transaction or address</h2><p>Search directly on this blockchain. We'll show the result and explain what the record means in plain English.</p><ChainSearch chain="ethereum"/></div>
  <div className="pt-chain-stats"><div><span>Latest block</span><strong>{recent[0]?"#"+n(recent[0].height):"—"}</strong><small>Newest Ethereum block</small></div><div><span>Average gas price</span><strong>{stats?.gas_prices?.average==null?"—":stats.gas_prices.average+" Gwei"}</strong><small>Network estimate; individual fees vary</small></div><div><span>Network</span><strong>Ethereum</strong><small>Mainnet</small></div></div>
  <div className="pt-chain-columns"><section className="pt-chain-section"><div className="pt-chain-section-head"><div><div className="pt-eyebrow">THE BLOCKCHAIN</div><h2>Latest Ethereum blocks</h2></div><span>Updated from live data</span></div><p>Each block records Ethereum transactions and contract activity. Open one to see its transactions.</p>{recent.length?recent.map((b:any)=><Link className="pt-chain-row" href={"/eth/block/"+b.hash} key={b.hash}><div><b>Block #{n(b.height)}</b><small>{n(b.tx_count??b.transactions_count)} transactions · {b.timestamp?new Date(b.timestamp).toLocaleString("en-US"):"Recently added"}</small></div><span>Explore →</span></Link>):<p>Ethereum block data is temporarily unavailable.</p>}</section><section className="pt-chain-section"><div className="pt-chain-section-head"><div><div className="pt-eyebrow">ON THE NETWORK</div><h2>Recent Ethereum transactions</h2></div><span>Recorded activity</span></div><p>Explore transfers, smart-contract calls and token movements, with explanations on each transaction page.</p>{txs.length?txs.map((t:any)=><Link className="pt-chain-row" href={"/eth/"+t.hash} key={t.hash}><div><b className="pt-chain-hash">{t.hash}</b><small>{t.method??"Transaction"} · {t.status??"Status unavailable"}</small></div><span>Explain →</span></Link>):<p>Recent Ethereum transactions are temporarily unavailable.</p>}</section></div><div className="pt-chain-foot"><Link href="/bitcoin">Explore Bitcoin →</Link><span>Data: Blockscout · Gas fees and network activity can change.</span></div>
 </main>
}