import Link from "next/link";
async function get(url:string){try{const r=await fetch(url,{next:{revalidate:25},signal:AbortSignal.timeout(7000)});return r.ok?await r.json():null}catch{return null}}
const n=(x:number|null|undefined)=>x==null?"—":new Intl.NumberFormat("en-US").format(x);
export default async function BitcoinAddress({params}:{params:{address:string}}){
 const address=params.address;const valid=/^(bc1[a-z0-9]{11,87}|[13][a-km-zA-HJ-NP-Z1-9]{25,34})$/.test(address);
 const [info,txs]=valid?await Promise.all([get("https://mempool.space/api/address/"+encodeURIComponent(address)),get("https://mempool.space/api/address/"+encodeURIComponent(address)+"/txs")]):[null,null];
 const funded=(info?.chain_stats?.funded_txo_sum??0)+(info?.mempool_stats?.funded_txo_sum??0);
 const spent=(info?.chain_stats?.spent_txo_sum??0)+(info?.mempool_stats?.spent_txo_sum??0);
 return <main className="pt-explorer pt-explorer-detail"><Link href="/explore">← Back to explorer</Link><div className="pt-eyebrow">BITCOIN ADDRESS EXPLORER</div><h1>Bitcoin address</h1><p className="pt-explorer-lead pt-explorer-hash">{address}</p>{info?<><p>This public address has received and spent Bitcoin. The estimated balance below is calculated from recorded outputs; it does not identify who controls this address.</p><div className="pt-explorer-stats"><div><span>Estimated balance</span><strong>{((funded-spent)/1e8).toFixed(8)} BTC</strong></div><div><span>Total received</span><strong>{(funded/1e8).toFixed(8)} BTC</strong></div><div><span>Total sent</span><strong>{(spent/1e8).toFixed(8)} BTC</strong></div><div><span>Confirmed transactions</span><strong>{n(info.chain_stats?.tx_count)}</strong></div></div><h2>Recent address activity</h2><p>Open any transaction to understand what happened, including inputs, outputs and fees.</p>{Array.isArray(txs)?txs.map((t:any)=><Link className="pt-explorer-block-row" href={"/btc/"+t.txid} key={t.txid}><span><b className="pt-explorer-hash">{t.txid}</b><small>{t.status?.confirmed?"Confirmed":"Pending"} · {n(t.fee)} sats fee</small></span><span>Explain →</span></Link>):<p>Recent activity unavailable.</p>}</>:<p>Address information is unavailable. Check the address or try again.</p>}</main>
}