import ChainSearch from "../components/ChainSearch";
import Link from "next/link";
export const metadata={title:"Bitcoin Explorer | Pending Tracker",description:"Explore Bitcoin blocks, recent transactions, the mempool and fee estimates in plain English."};
async function get(url:string){try{const r=await fetch(url,{next:{revalidate:15},signal:AbortSignal.timeout(7000)});return r.ok?await r.json():null}catch{return null}}
const n=(v:number|null|undefined)=>v==null?"—":new Intl.NumberFormat("en-US").format(v);
export default async function BitcoinExplorer(){
 const [blocks,pool,fees,transactions]=await Promise.all([get("https://mempool.space/api/blocks"),get("https://mempool.space/api/mempool"),get("https://mempool.space/api/v1/fees/recommended"),get("https://mempool.space/api/mempool/recent")]);
 const recent=Array.isArray(blocks)?blocks.slice(0,12):[];
 const txs=Array.isArray(transactions)?transactions.slice(0,12):[];
 return <main className="pt-chain-page">
  <div className="pt-chain-breadcrumb"><Link href="/">Home</Link><span> / </span> Bitcoin Explorer</div>
  <div className="pt-chain-hero"><div className="pt-chain-symbol pt-chain-bitcoin">₿</div><div><div className="pt-eyebrow">BITCOIN BLOCKCHAIN EXPLORER</div><h1>Explore Bitcoin.</h1><p>See what is happening on Bitcoin in plain English. Every block and transaction leads to the underlying details, with explanations before the technical data.</p></div></div>
  <div className="pt-chain-search"><h2>Find a Bitcoin transaction or address</h2><p>Search directly on this blockchain. We'll show the result and explain what the record means in plain English.</p><ChainSearch chain="bitcoin"/></div>
  <div className="pt-chain-stats"><div><span>Latest block</span><strong>{recent[0]?"#"+n(recent[0].height):"—"}</strong><small>Newest confirmed Bitcoin block</small></div><div><span>Waiting transactions</span><strong>{n(pool?.count)}</strong><small>Transactions currently in the mempool</small></div><div><span>Priority fee estimate</span><strong>{fees?.fastestFee==null?"—":fees.fastestFee+" sat/vB"}</strong><small>Estimate, not a confirmation guarantee</small></div></div>
  <div className="pt-chain-columns"><section className="pt-chain-section"><div className="pt-chain-section-head"><div><div className="pt-eyebrow">THE BLOCKCHAIN</div><h2>Latest Bitcoin blocks</h2></div><span>Updated from live data</span></div><p>Blocks are batches of confirmed transactions. Select one to inspect its contents.</p>{recent.length?recent.map((b:any)=><Link className="pt-chain-row" href={"/btc/block/"+b.id} key={b.id}><div><b>Block #{n(b.height)}</b><small>{n(b.tx_count)} transactions · {new Date(b.timestamp*1000).toLocaleString("en-US")}</small></div><span>Explore →</span></Link>):<p>Bitcoin block data is temporarily unavailable.</p>}</section><section className="pt-chain-section"><div className="pt-chain-section-head"><div><div className="pt-eyebrow">THE MEMPOOL</div><h2>Recent Bitcoin transactions</h2></div><span>Not yet confirmed</span></div><p>The mempool is where broadcast transactions wait to be included in a block.</p>{txs.length?txs.map((t:any)=><Link className="pt-chain-row" href={"/btc/"+t.txid} key={t.txid}><div><b className="pt-chain-hash">{t.txid}</b><small>{t.fee==null?"Fee unavailable":n(t.fee)+" sats fee"} · {t.vsize==null?"Size unavailable":n(t.vsize)+" vB"}</small></div><span>Explain →</span></Link>):<p>Recent mempool transactions are temporarily unavailable.</p>}</section></div><div className="pt-chain-foot"><Link href="/ethereum">Explore Ethereum →</Link><span>Data: mempool.space · Estimates are not guarantees.</span></div>
 </main>
}